spring.application.name=module02

spring.datasource.url=jdbc:mysql://localhost:3306/departmentdb?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=1234
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
